apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.networking.istio.io
  labels:
    app: istio-pilot
spec:
  group: networking.istio.io
  names:
    kind: Gateway
    plural: gateways
    singular: gateway
    shortNames:
      - gw
    categories:
      - istio-io
      - networking-istio-io
  scope: Namespaced
  version: v1alpha3
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: commongateway
  annotations:
    stoakes.github.com/cluster: some_service
    stoakes.github.com/hostname: "*,hello.example.org"
spec:
  selector:
    app: envoy
  servers:
    - port:
        number: 8000
        name: http
        protocol: HTTP
      hosts:
        - "*"
